/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IPhChartScatter: typeof import('~icons/ph/chart-scatter')['default']
    IPhChartScatterBold: typeof import('~icons/ph/chart-scatter-bold')['default']
    IPhChartScatterFill: typeof import('~icons/ph/chart-scatter-fill')['default']
  }
}
