/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IPhCalendar: typeof import('~icons/ph/calendar')['default']
    IPhCalendarFill: typeof import('~icons/ph/calendar-fill')['default']
    IPhInfoFill: typeof import('~icons/ph/info-fill')['default']
    IPhWarningDiamondFill: typeof import('~icons/ph/warning-diamond-fill')['default']
  }
}
