/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IPhArrowRight: typeof import('~icons/ph/arrow-right')['default']
  }
}
